### ISSUE TITLE
Knowledge page: long term to-do

### ISSUE THREAD

**Issue by DannyDuckschDev** [feministCoding/gender-data-webapp#10]
- [ ] language options - german | englisch
- [ ] add podcats as a media type as well
- [ ] add content
- [ ] display content description more userfriendly
- [ ] dsplay latest added content at the top of each content type
