### ISSUE TITLE
Support offers page: long term to-do

### ISSUE THREAD

**Issue by DannyDuckschDev** [feministCoding/gender-data-webapp#12]
- [ ] searchbar for map
- [ ] complete map of Outpatient clinic for victims
- [ ] styling text in gernal
- [ ] write final text for the content
